### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d0ubl3puls4r** [chrispetrou/HRShell#2]
When using the commands below you receive the respective errors:

lubuntu-lubuntu@192.168.1.10:~/lubuntu$ screenshot
**ERROR: Pillow module is not installed**

lubuntu-lubuntu@192.168.1.10:~/lubuntu$ show shellcodes
**[ERROR] There are no shellcodes available.**

how to solve these problems
Thanks.

**Comment by chrispetrou** [comment]
Hi @d0ubl3puls4r ,

Both errors you posted pretty much describe what's wrong. In the first error, the system you are executing `client.py` doesn't have [`pillow`](https://pillow.readthedocs.io/en/stable/) module installed which is needed for the screenshot-command to work. In order to resolve that you can install it through `server.py` since HRShell supports remote python-module installations.

The second error indicates that you haven't edit `shellcodes/utils.py` script such that it contains some pre-generated shellcode(s) of your choice, as described in the [README](https://github.com/chrispetrou/HRShell#setmodify-shellcode). You can also edit the `shellcodes/utils.py` script even after you've launched `server.py`.
